### PR TITLE
Backend Consistency Fixes

### PR DESCRIPTION
**Pull request by jeremylt**
This is a follow-up to https://github.com/CEED/libCEED/pull/1312 applying the same changes to the backends

Generally I 

* Use `snake_case` consistently, like in the interface level

* Pull almost all variable declarations up to the top of their scope

* Use `const` where able

* Limit variable's scopes where practical (could do more of this in the future)

### CODE REVIEW

**Comment by jeremylt** [comment]
@jrwrigh will you be able to manually verify the SYCL changes once this PR is ready for review? Those are the only ones I haven't checked yet.

**Comment by jrwrigh** [comment]
Sure, let me know when you want them done.

File: backends/sycl-ref/ceed-sycl-ref-operator.sycl.cpp [hunk 1]
```diff
@@ -1251,35 +1280,35 @@ static int CeedOperatorLinearAssembleFallback_Sycl(sycl::queue &sycl_queue, cons
   // This kernel assumes B_in and B_out have the same number of quadrature points and basis points.
```
Comment (jeremylt) [inline backends/sycl-ref/ceed-sycl-ref-operator.sycl.cpp:1280]: Note - we merged a lot of dead code here in the SYCL backend. I don't love that.

**Comment by jeremylt** [comment]
> Sure, let me know when you want them done.

Ok, I think we're OK to test. Any errors are likely due to bad copy-paste on my part.

**Comment by jeremylt** [comment]
@jrwrigh will you have a chance to check that the SYCL test suite passes sometime this week? I'd like to get this bandaid ripped off since this will be a bit disruptive of a PR

**Comment by jrwrigh** [comment]
Sorry, dropped the ball on this. I'll try and do it later today.

**Comment by jeremylt** [comment]
> There are more errors, but I think this encapsulates all the "no member named". Clangd catches these too. That said, I'm not sure how to handle them or how they got to this point. For example the `impl->num_active_in` doesn't appear to have similar named member before or after this PR.

I think this fixes those issues? (force pushed)

**Comment by jrwrigh** [comment]
I've pushed up some other typo fixes so it compiles now. But I'm getting test failures on t at the moment such as:
```
# $ build/t554-operator /gpu/sycl/gen
not ok 3
  ERROR: returncode = 254
  FAILURE 0: stderr
    Output:
/home/jrwrigh/software/libCEED/backends/sycl/ceed-sycl-compile.sycl.cpp:73 in CeedJitCompileSource_Sycl(): ocloc reported compilation errors: {
3:1609:245: error: expected ')'
kernel void CeedKernelSyclGenOperator_setup(const CeedInt num_elem, global void* ctx, global const FieldsInt_Sycl* indices, global Fields_Sycl* fields, global const Fields_Sycl* B, global const Fields_Sycl* G, global const CeedScalar * rstrict W) {
                                                                                                                                                                                                                                                    ^
3:1609:44: note: to match this '('
kernel void CeedKernelSyclGenOperator_setup(const CeedInt num_elem, global void* ctx, global const FieldsInt_Sycl* indices, global Fields_Sycl* fields, global const Fields_Sycl* B, global const Fields_Sycl* G, global const CeedScalar * rstrict W) {
                                           ^
3:1642:20: error: use of undeclared identifier 'W'
    Weight1d(Q_1D, W, r_t_0);
                   ^

Build failed with error code: -11

}

  FAILURE 1: stdout
    Output:
Command was: ocloc -q -spv_only -device pvc -64 -options "-cl-std=CL3.0 -Dint32_t=int" -file main.cl
```

**Comment by jeremylt** [comment]
I think the latest should fix it.

**Comment by jrwrigh** [comment]
Welcome! All the tests pass now except for fluids, but that's actually because of an incompatability I introduced in #1303; Sycl isn't happy with `dxdX_q` in 
https://github.com/CEED/libCEED/blob/dfc85eef17dc5c28b65ac5988770d3001ba75f16/examples/fluids/qfunctions/setupgeo_helpers.h#L103-L104

which I guess is fair. But I can fix that up in a separate PR (probably won't get to it till tomorrow).

**Review by jrwrigh — APPROVED** [review]
Passes all Sycl tests (except for the above mentioned fluids test that is out of scope from this PR).

**Comment by jrwrigh** [comment]
I've gone ahead and pushed up the changes necessary for the fluids code to compile on Sunspot as well. I can move that to a separate PR if you want.

**Comment by sebastiangrimberg** [comment]
> I'd like to get this bandaid ripped off since this will be a bit disruptive of a PR

Thanks for taking care of this! I'll go through the fun of rebasing my PRs today.
